/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author alunosenac
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtTitulo = new javax.swing.JLabel();
        txtLogin = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtSenha = new javax.swing.JLabel();
        txtPerfil = new javax.swing.JLabel();
        txtConfirmarSenha1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoId = new javax.swing.JTextField();
        campoLogin = new javax.swing.JTextField();
        campoConfirmarSenha = new javax.swing.JPasswordField();
        campoSenha = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTelaFundo = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtTitulo.setForeground(java.awt.Color.white);
        txtTitulo.setText("Cadastro");
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, 30));

        txtLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtLogin.setForeground(java.awt.Color.white);
        txtLogin.setText("*LOGIN:");
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txtId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtId.setForeground(java.awt.Color.white);
        txtId.setText("*ID:");
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        txtNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNome.setForeground(java.awt.Color.white);
        txtNome.setText("*NOME:");
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSenha.setForeground(java.awt.Color.white);
        txtSenha.setText("*SENHA:");
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        txtPerfil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPerfil.setForeground(java.awt.Color.white);
        txtPerfil.setText("*PERFIL:");
        getContentPane().add(txtPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txtConfirmarSenha1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtConfirmarSenha1.setForeground(java.awt.Color.white);
        txtConfirmarSenha1.setText("*CONFIRMAR SENHA:");
        getContentPane().add(txtConfirmarSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        campoNome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 390, -1));

        campoId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdActionPerformed(evt);
            }
        });
        getContentPane().add(campoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 390, -1));

        campoLogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoginActionPerformed(evt);
            }
        });
        getContentPane().add(campoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 390, -1));

        campoConfirmarSenha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campoConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoConfirmarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(campoConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 390, 20));

        campoSenha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 390, 20));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João", "Richarlysson", "Albert" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        btnCadastrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(null);
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 70, 30));

        btnPesquisar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 100, 30));

        btnAlterar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, 30));

        btnExcluir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, 30));

        btnLimpar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, 30));

        btnCancelar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 8)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("*Obrigatório");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        lblTelaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/pexels-jonathan-borba-14348489.jpg"))); // NOI18N
        getContentPane().add(lblTelaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdActionPerformed

    private void campoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginActionPerformed

    private void campoConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoConfirmarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoConfirmarSenhaActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JPasswordField campoConfirmarSenha;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblTelaFundo;
    private javax.swing.JLabel txtConfirmarSenha1;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtPerfil;
    private javax.swing.JLabel txtSenha;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
